# port
server:
  port: 8080
  domain: http://192.168.1.254
  servlet:
    context-path: /material
# db
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/shop
    username: root
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  jmx:
    default-domain: read
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy/MM/dd HH:mm:ss

# uploading
data.path: C:/app/res/media/
data.program: D:/app/res/program/

# logging
logging:
  level:
#    com.foxconn.fii: INFO
    #    org.hibernate.SQL: DEBUG
    #org.springframework.jdbc.core.JdbcTemplate: DEBUG

#cron
batch:
  cron:
    sync-daily: 0 0 7 * * *
    sync-shift:
      shift-day: 0 0 19 * * *
      shift_night: 0 0 7 * * *
    sync-four-lession:
      lession-one: 0 0 13 * * *
      lession-two: 0 0 19 * * *
      lession-three: 0 0 1 * * *
      lession-four: 0 0 7 * * *