# port
server:
  port: 1996
  servlet:
    context-path: /
# db
spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/travel_blog
    username: root
    password: 12345678
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  jackson:
    time-zone: Asia/Ho_Chi_Minh
    date-format: yyyy/MM/dd HH:mm:ss

# uploading
data:
  path: C:/AppServ/www/project/JavaSpring/test/

# logging
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.springframework.web.client.RestTemplate: DEBUG

jwt:
  secret: travel-blog